/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package edu.itsco;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 5;
  /** RegularExpression Id. */
  int INTEGER = 6;
  /** RegularExpression Id. */
  int DECIMAL = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int PRINT = 9;
  /** RegularExpression Id. */
  int READ = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int SELECT = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int BREAK = 15;
  /** RegularExpression Id. */
  int FOR = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int SUMA = 19;
  /** RegularExpression Id. */
  int RESTA = 20;
  /** RegularExpression Id. */
  int MULTI = 21;
  /** RegularExpression Id. */
  int DIV = 22;
  /** RegularExpression Id. */
  int MOD = 23;
  /** RegularExpression Id. */
  int IGUAL = 24;
  /** RegularExpression Id. */
  int MAYOR = 25;
  /** RegularExpression Id. */
  int MENOR = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int NOT = 29;
  /** RegularExpression Id. */
  int AP = 30;
  /** RegularExpression Id. */
  int CP = 31;
  /** RegularExpression Id. */
  int AL = 32;
  /** RegularExpression Id. */
  int CL = 33;
  /** RegularExpression Id. */
  int PC = 34;
  /** RegularExpression Id. */
  int DP = 35;
  /** RegularExpression Id. */
  int COMA = 36;
  /** RegularExpression Id. */
  int digito = 37;
  /** RegularExpression Id. */
  int letra = 38;
  /** RegularExpression Id. */
  int ID = 39;
  /** RegularExpression Id. */
  int INT_VAL = 40;
  /** RegularExpression Id. */
  int DEC_VAL = 41;
  /** RegularExpression Id. */
  int STR_VAL = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"program\"",
    "\"integer\"",
    "\"decimal\"",
    "\"string\"",
    "\"print\"",
    "\"read\"",
    "\"if\"",
    "\"else\"",
    "\"select\"",
    "\"case\"",
    "\"break\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "<digito>",
    "<letra>",
    "<ID>",
    "<INT_VAL>",
    "<DEC_VAL>",
    "<STR_VAL>",
  };

}
